name: dmsn2026
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  animated_bottom_navigation_bar: ^1.4.0
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0   # FIX: dependencia requerida por castdb.dart para usar join()
  intl: ^0.20.2  
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: minecraft_fot_esp
      fonts:
        - asset: fonts/minecraft_fot_esp.ttf
