// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrIBvhtUgS6_FXJKq7TgXIamoNNIbBBk',
    appId: '1:836701596999:web:006067c5f19f2c3cd47062',
    messagingSenderId: '836701596999',
    projectId: 'dmsn2026-junior',
    authDomain: 'dmsn2026-junior.firebaseapp.com',
    storageBucket: 'dmsn2026-junior.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPecAM5leqpG_RJBsB_raSLJ-YVK432Z8',
    appId: '1:836701596999:android:7a3efbff174e27a9d47062',
    messagingSenderId: '836701596999',
    projectId: 'dmsn2026-junior',
    storageBucket: 'dmsn2026-junior.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRCgAK3aeI_GKQS6YsiRWoYmvUbivv4c',
    appId: '1:836701596999:ios:bc21d72bf9b569aed47062',
    messagingSenderId: '836701596999',
    projectId: 'dmsn2026-junior',
    storageBucket: 'dmsn2026-junior.firebasestorage.app',
    iosBundleId: 'com.example.dmsn2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRCgAK3aeI_GKQS6YsiRWoYmvUbivv4c',
    appId: '1:836701596999:ios:bc21d72bf9b569aed47062',
    messagingSenderId: '836701596999',
    projectId: 'dmsn2026-junior',
    storageBucket: 'dmsn2026-junior.firebasestorage.app',
    iosBundleId: 'com.example.dmsn2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYrIBvhtUgS6_FXJKq7TgXIamoNNIbBBk',
    appId: '1:836701596999:web:31d89520fb9be48fd47062',
    messagingSenderId: '836701596999',
    projectId: 'dmsn2026-junior',
    authDomain: 'dmsn2026-junior.firebaseapp.com',
    storageBucket: 'dmsn2026-junior.firebasestorage.app',
  );
}
